version: '3.8'

services:
  jekyll-dev:
    image: mcr.microsoft.com/devcontainers/jekyll:2-bullseye
    ports:
      - "4000:4000" # Host:Container port mapping for Jekyll
    volumes:
      - .:/workspaces:cached
    command: sleep infinity
